added all database/week2 files
rajanibusani/hyf-homework pull request #16
Opened 2021-01-19 17:31 UTC by rajanibusani

DB/week2 HW

2021-01-23 16:10 UTC, aina21 requested changes
good job :)
for part4, what is the difference between shipment and order? Do you need product_id in the shipment table?

2021-01-23 16:10 UTC, aina21 commented on databases/week2/wk2_part3.sql
> +FROM user_task
I believe we don't have user_task table, you can use user

2021-01-23 16:10 UTC, aina21 commented on databases/week2/wk2_part3.sql
> +WHERE user.name = 'Donald Duck' AND status.name = 'Not started';
I think you only need to join task table to user and status, you don't need  user_task table, 
let's try again, the result should be zero :)

2021-01-23 16:10 UTC, aina21 commented on databases/week2/wk2_part3.sql
> +WHERE user.name = 'Maryrose Meadows' AND month(created)=09;
I don't have a user_task table, so I can't test your query. you can write with only one join.

2021-01-23 16:29 UTC, aina21 approved these changes

2021-01-27 13:25 UTC, sofiiadidovych reviewed
Good job! everything is clean and clear! Keep up this way))

2021-01-27 22:06 UTC, rajanibusani commented
> Good job! everything is clean and clear! Keep up this way))

@sofiiadidovych Thank you sofia....

2021-02-12 09:22 UTC, merged