added todo-app files
rajanibusani/hyf-homework pull request #21
Opened 2021-02-22 22:05 UTC by rajanibusani

2021-02-26 17:27 UTC, Ekamba requested changes
Hi @rajanibusani, instead of writing your function's name like this `Todoitems` you have to do this: `TodoItems`. In your RenderTodos I don't thing you have to wrap everything inside `<ol>...</ol>`. Remember olso to wrap li tag inside of <ul> like this `<ul> <li>..</li> </ul>`. You do not have wrap your component inside brace like you did inside App.js

2021-02-27 16:08 UTC, khjcph commented on react/week1/todo-app/src/App.js
> +  return (
maybe work a bit with the formatting here. for example

    return <div className="todo-app">{<Todolist />}</div>;

is a little easier to read

2021-02-27 16:09 UTC, khjcph commented on react/week1/todo-app/src/todos.js
> +const Todoitems = ({ task, deadline }) => {
great that you destructure here!

2021-02-27 16:11 UTC, khjcph commented on react/week1/todo-app/src/todos.js
> +                            <Todoitems task={todo.task} deadline={todo.deadline} />
I don't know if this was covered in class, but lists in react should actually have a unique key. You can read more about those here: https://reactjs.org/docs/lists-and-keys.html#keys. If you would like to you can try to implement keys for your list.

2021-02-27 16:14 UTC, khjcph commented on react/week1/todo-app/src/todos.js
> +const RenderTodos = ({ todos }) => {
great use of destructuring!

2021-02-27 16:14 UTC, khjcph commented on react/week1/todo-app/src/todos.js
> +const Todolist = () => {
maybe this should be `TodoList`

2021-02-27 16:16 UTC, khjcph approved these changes
Great work!! 👍

I left a few comments that you can look at if you want. They are mostly about formatting. This is much easier if using a formatter / linter inside your code editor. I hope we will get to cover that in class :)

2021-02-27 19:43 UTC, rajanibusani commented
> Great work!! 
> 
> I left a few comments that you can look at if you want. They are mostly about formatting. This is much easier if using a formatter / linter inside your code editor. I hope we will get to cover that in class :)

Thank you so much for your comments,i will change them as you suggested...tq

2021-03-02 19:42 UTC, merged